dist: xenial
language: bash
services: docker

env:
  matrix:
    - BASE_VERSION=latest

before_script:
  - docker build -t cups-test --build-arg BASE_VERSION=$BASE_VERSION .
  - VERSION=$(docker run --rm -it cups-test dpkg -l cups |grep ii |awk '{print $3}')

script:
  # test always passes, if cups comes to life within 20 seconds
  - echo "Base image version $BASE_VERSION CUPS $VERSION"
  - >
    echo "Starting cups...";
    docker run cups-test;
    sleep 20;
    docker exec cups-test /healthcheck.sh && echo "container HEALTHY";
    docker ps;

