#dist: xenial # use default
language: bash
services: docker

env:
  matrix:
    - UBUNTU_VERSION=latest
    - UBUNTU_VERSION=focal
    - UBUNTU_VERSION=eoan
    - UBUNTU_VERSION=disco
    - UBUNTU_VERSION=bionic
    - UBUNTU_VERSION=xenial

before_script:
  - docker build -t airprint-travis --build-arg UBUNTU_VERSION=$UBUNTU_VERSION .
  - VERSION=$(docker run --rm -it --entrypoint dpkg airprint-travis -l cups |grep ii |awk '{print $3}')

script:
  # travis always passes, if cups comes to life
  - echo "Ubuntu version = $UBUNTU_VERSION CUPS = $VERSION"
  - >
    echo "Starting cups...";
    docker create --name airprint-test airprint-travis;
    docker start airprint-test;
    docker exec airprint-test bash -c 'while ! cupsctl -h localhost --share-printers 2>/dev/null; do echo -n "."; sleep 1; done';
    while [ -z "$(docker ps -f name='airprint-test' --format '{{ .Status }}' |grep '(healthy)')" ]; do echo -n "."; sleep 1; done;
    docker ps -f name='airprint-test';
