dist: xenial
language: bash
services: docker

env:
  matrix:
    - BASE_VERSION=latest

before_script:
  - docker build -t airprint-travis --build-arg BASE_VERSION=$BASE_VERSION .
  - VERSION=$(docker run --rm -it airprint-travis dpkg -l cups |grep ii |awk '{print $3}')

script:
  # travis always passes, if cups comes to life
  - echo "Base image version $BASE_VERSION CUPS $VERSION"
  - >
    echo "Starting cups...";
    docker create --name airprint-test airprint-travis;
    docker start airprint-test;
    docker exec cups-zion bash -c 'while ! cupsctl > /dev/null 2>&1; do echo -n "."; sleep 1; done';
    docker ps;

