# Required variables
# REPO, IMAGE_NAME
# PLATFORMS = linux/amd64,linux/arm64/v8,linux/arm/v7,...
# DOCKER_USER, DOCKER_PASS
version: 2.1
aliases:
  - &docker
      - image: docker:dind
  - &steps
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Install docker buildx
          command: |
            #apt update && apt install -y curl
            mkdir -p ~/.docker/cli-plugins
            baseUrl="https://github.com/docker/buildx/releases/download"
            fileName="buildx-v<< parameters.version >>.linux-amd64"
            url="${baseUrl}/v<< parameters.version >>/${fileName}"
            curl -sSL -o ~/.docker/cli-plugins/docker-buildx $url
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            echo 'export DOCKER_CLI_EXPERIMENTAL="enabled"' >> $BASH_ENV
      - run:
          name: Prepare docker buildx
          command: |
            docker buildx install
            docker version
            docker buildx version
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create xbuilder
            docker buildx create xbuilder --name xbuilder --use
            docker buildx inspect --bootstrap
      - run:
          name: Build all platforms
          command: |
            docker buildx build --progress plain --platform $PLATFORMS --build-arg INLFUXDB_VERSION=$UBUNTU_VERSION -t $REPO/$IMAGE_NAME:$TAG .
      - run:
          name: Build and push all platforms
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin &> /dev/null || exit 1
              docker buildx build --progress plain --platform $PLATFORMS --build-arg INLFUXDB_VERSION=$UBUNTU_VERSION -t $REPO/$IMAGE_NAME:$TAG --push .
            fi
jobs:
  build_latest:
    parameters:
      version:
        default: 0.5.1
        type: string
    environment:
      UBUNTU_VERSION: latest
      TAG: latest
    docker: *docker
    steps: *steps
  build_focal:
    parameters:
      version:
        default: 0.5.1
        type: string
    environment:
      UBUNTU_VERSION: focal
      TAG: focal
    docker: *docker
    steps: *steps
  build_bionic:
    parameters:
      version:
        default: 0.5.1
        type: string
    environment:
      UBUNTU_VERSION: bionic
      TAG: bionic
    docker: *docker
    steps: *steps
  build_xenial:
    parameters:
      version:
        default: 0.5.1
        type: string
    environment:
      UBUNTU_VERSION: xenial
      TAG: xenial
    docker: *docker
    steps: *steps

workflows:
  version: 2
  weekly:
    triggers:
      - schedule:
          # mondays, 6:03 am, UTC
          cron: "3 6 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_xenial
      - build_bionic
      - build_focal
      - build_latest
  build:
    jobs:
      - build_xenial
      - build_bionic
      - build_focal
      - build_latest